{
 "title": "Jenkins Application Build Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Build Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Successful Builds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "build_type" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "query": "SELECT count(\"build_number\") FROM \"build_stats\" WHERE (\"build_type\" = 'BUILD' AND \"build_result\" = 'SUCCESS') AND $timeFilter GROUP BY \"build_type\"",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "BUILD" },
      { "condition": "AND", "key": "build_result", "operator": "=", "value": "SUCCESS" }
     ]
    }
   ]
  },
  {
   "title": "Total Failed Builds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "build_type" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "query": "SELECT count(\"build_number\") FROM \"build_stats\" WHERE (\"build_type\" = 'BUILD' AND \"build_result\" = 'FAILURE') AND $timeFilter GROUP BY \"build_type\"",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "BUILD" },
      { "condition": "AND", "key": "build_result", "operator": "=", "value": "FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Total Aborted Builds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "build_type" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "BUILD" },
      { "condition": "AND", "key": "build_result", "operator": "=", "value": "ABORTED" }
     ]
    }
   ]
  },
  {
   "title": "Application Build Summary",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "measurement": "build_stats",
     "select": [
      [
       { "params": [ "component_f" ], "type": "field" }
      ],
      [
       { "params": [ "is_success" ], "type": "field" }
      ],
      [
       { "params": [ "is_failure" ], "type": "field" }
      ],
      [
       { "params": [ "is_abort" ], "type": "field" }
      ],
      [
       { "params": [ "build_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "BUILD" }
     ]
    }
   ]
  },
  {
   "title": "Build Trends",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_build_result",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "build_result" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build_stats",
     "query": "SELECT mean(\"build_time\") FROM \"build_stats\" WHERE (\"build_type\" = 'BUILD') AND $timeFilter GROUP BY time($__interval), \"build_result\" fill(null)",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "BUILD" }
     ]
    }
   ]
  },
  { "title": "Application Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Build customer_app",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_build_result",
     "groupBy": [
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "build_result" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "customer_app" },
      { "condition": "AND", "key": "build_type", "operator": "=", "value": "BUILD" }
     ]
    }
   ]
  },
  {
   "title": "Build product_app",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_build_result",
     "groupBy": [
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "build_result" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "product_app" },
      { "condition": "AND", "key": "build_type", "operator": "=", "value": "BUILD" }
     ]
    }
   ]
  },
  {
   "title": "Build Version Stats",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component - $tag_build_version ",
     "groupBy": [
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "build_version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "build_stats",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "BUILD" }
     ]
    }
   ]
  },
  {
   "title": "customer_app",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_build_result",
     "groupBy": [
      { "params": [ "build_type" ], "type": "tag" },
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "build_result" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "query": "SELECT \"build_time\" FROM \"build_stats\" WHERE (\"build_type\" = 'BUILD' AND \"component\" = 'customer_app') AND $timeFilter GROUP BY \"build_type\", \"component\"",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "BUILD" },
      { "condition": "AND", "key": "component", "operator": "=", "value": "customer_app" }
     ]
    }
   ]
  },
  {
   "title": "product_app",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_build_result",
     "groupBy": [
      { "params": [ "build_type" ], "type": "tag" },
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "build_result" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "query": "SELECT \"build_time\" FROM \"build_stats\" WHERE (\"build_type\" = 'BUILD' AND \"component\" = 'customer_app') AND $timeFilter GROUP BY \"build_type\", \"component\"",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "BUILD" },
      { "condition": "AND", "key": "component", "operator": "=", "value": "product_app" }
     ]
    }
   ]
  }
 ]
}