{
 "title": "Jenkins Application Deploy Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Environment",
    "query": "show tag values with key=environment"
   },
   {
    "name": "DataCenter",
    "label": "DataCenter",
    "query": "show tag values from build_stats with key=dc where environment='$Environment' "
   }
  ]
 },
 "panels": [
  { "title": "Deploy Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Deploy Builds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "build_type" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "query": "SELECT count(\"build_number\") FROM \"build_stats\" WHERE (\"build_type\" = 'BUILD' AND \"build_result\" = 'SUCCESS') AND $timeFilter GROUP BY \"build_type\"",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "DEPLOY" },
      { "condition": "AND", "key": "build_result", "operator": "=", "value": "SUCCESS" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$DataCenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Failed Deploys",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "build_type" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "query": "SELECT count(\"build_number\") FROM \"build_stats\" WHERE (\"build_type\" = 'BUILD' AND \"build_result\" = 'FAILURE') AND $timeFilter GROUP BY \"build_type\"",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "DEPLOY" },
      { "condition": "AND", "key": "build_result", "operator": "=", "value": "FAILURE" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$DataCenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Aborted Deploys",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "build_type" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "DEPLOY" },
      { "condition": "AND", "key": "build_result", "operator": "=", "value": "ABORTED" },
      { "condition": "AND", "key": "envronment", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$DataCenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Application Deploy Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "measurement": "build_stats",
     "select": [
      [
       { "params": [ "component_f" ], "type": "field" }
      ],
      [
       { "params": [ "is_success" ], "type": "field" }
      ],
      [
       { "params": [ "is_failure" ], "type": "field" }
      ],
      [
       { "params": [ "is_abort" ], "type": "field" }
      ],
      [
       { "params": [ "build_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "DEPLOY" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$DataCenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Deploy Trends",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_build_result",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "build_result" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build_stats",
     "query": "SELECT mean(\"build_time\") FROM \"build_stats\" WHERE (\"build_type\" = 'DEPLOY') AND $timeFilter GROUP BY time($__interval), \"build_result\" fill(null)",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "DEPLOY" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$DataCenter$/" }
     ]
    }
   ]
  },
  { "title": "Application Deploy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Deploy customer_app",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_build_result",
     "groupBy": [
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "build_result" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "customer_app" },
      { "condition": "AND", "key": "build_type", "operator": "=", "value": "DEPLOY" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$DataCenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Deploy product_app",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_build_result",
     "groupBy": [
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "build_result" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "product_app" },
      { "condition": "AND", "key": "build_type", "operator": "=", "value": "DEPLOY" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$DataCenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Deploy Version Stats",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component - $tag_build_version ",
     "groupBy": [
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "build_version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "build_stats",
     "select": [
      [
       { "params": [ "build_number" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "DEPLOY" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$DataCenter$/" }
     ]
    }
   ]
  },
  {
   "title": "customer_app",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_build_result",
     "groupBy": [
      { "params": [ "build_type" ], "type": "tag" },
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "build_result" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "query": "SELECT \"build_time\" FROM \"build_stats\" WHERE (\"build_type\" = 'BUILD' AND \"component\" = 'customer_app') AND $timeFilter GROUP BY \"build_type\", \"component\"",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "DEPLOY" },
      { "condition": "AND", "key": "component", "operator": "=", "value": "customer_app" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$DataCenter$/" }
     ]
    }
   ]
  },
  {
   "title": "product_app",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_build_result",
     "groupBy": [
      { "params": [ "build_type" ], "type": "tag" },
      { "params": [ "component" ], "type": "tag" },
      { "params": [ "build_result" ], "type": "tag" }
     ],
     "measurement": "build_stats",
     "query": "SELECT \"build_time\" FROM \"build_stats\" WHERE (\"build_type\" = 'BUILD' AND \"component\" = 'customer_app') AND $timeFilter GROUP BY \"build_type\", \"component\"",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "build_type", "operator": "=", "value": "DEPLOY" },
      { "condition": "AND", "key": "component", "operator": "=", "value": "product_app" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "dc", "operator": "=", "value": "us-east" }
     ]
    }
   ]
  }
 ]
}